apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: sbarnoussi
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: mongo:latest
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: "100m"       # 1/10 CPU
            memory: "100Mi"   # 100 MB
          limits:
            cpu: "200m"       # 1/5 CPU
            memory: "200Mi"   # 200 MB
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: sbarnoussi
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
