apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb
  namespace: sbarnoussi
  labels:
    app: webdb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webdb
  template:
    metadata:
      labels:
        app: webdb
    spec:
      containers:
      - name: webdb-container
        image: bellator2611/flask_app:v2
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_HOST
          value: "10.43.154.225:27017"  
        resources:
          requests:
            cpu: "100m"       # 1/10 CPU
            memory: "100Mi"   # 100 MB
          limits:
            cpu: "200m"       # 1/5 CPU
            memory: "200Mi"   # 200 MB
---
apiVersion: v1
kind: Service
metadata:
  name: webdb-service
  namespace: sbarnoussi
spec:
  selector:
    app: webdb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
