version: "3.8"

services:
  flask_app:
    build:
      context: .
    container_name: flask_app
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app_network
    

networks:
  app_network:


