apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mongo-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["mongosh"]
          args:
            - "--host"
            - "mongodb-0.mongodb-service.{{ .Release.Namespace }}.svc.cluster.local"
            - "--eval"
            - >
              rs.initiate({
                _id: "rs0",
                members: [
                  { _id: 0, host: "mongodb-0.mongodb-service.{{ .Release.Namespace }}.svc.cluster.local:27017" },
                  { _id: 1, host: "mongodb-1.mongodb-service.{{ .Release.Namespace }}.svc.cluster.local:27017" },
                  { _id: 2, host: "mongodb-2.mongodb-service.{{ .Release.Namespace }}.svc.cluster.local:27017" }
                ]
              });
