apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 27017
  clusterIP: None  # Service Headless pour découverte DNS
  selector:
    app: mongodb
