version: "3.8"

services:
  # Flask App Without Database
  flask_no_db:
    build:
      context: .
      dockerfile: Dockerfile_no_db
    container_name: flask_no_db
    ports:
      - "5001:5000"
    networks:
      - app_network

  # Flask App With Database
  flask_with_db:
    build:
      context: .
      dockerfile: Dockerfile_with_db
    container_name: flask_with_db
    ports:
      - "5002:5000"
    networks:
      - app_network
    depends_on:
      - mongodb

  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app_network
    

  # NGINX Load Balancer
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - app_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  app_network:
    name: challenge4_app_network


