namespace: sbarnoussi

replicaCount: 3

image:
  webnodb: "bellator2611/flask-docker-app:v2"
  webdb: "bellator2611/flask_app:v4"
  mongodb: "mongo:latest"

ports:
  webnodb: 5000
  webdb: 5000
  mongodb: 27017

hostnames:
  ingressHost: net4255.luxbulb.org
  webnodb: webnodb
  webdb: webdb

resources:
  requests:
    cpu: "0.1"
    memory: "100Mi"
  limits:
    cpu: "0.2"
    memory: "200Mi"

mongodb:
  image: mongo:latest
  username: admin
  password: admin
  dbName: flask_app_db
  collectionName: requests
  storage: "300Mi"